apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: public-ui
  name: public-ui
spec:
  type: NodePort
  ports:
  - name: headless
    port: 8010
    nodePort: 30183
  selector:
    io.kompose.service: public-ui
status:
  loadBalancer: {}

