pipeline:
  build_docker_image:
    image: docker:17.09.0-ce
    privileged: true
    when:
      branch: [master, develop]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - ./docker-build.sh egar-public-ui
  deploy_docker_latest_image:
    image: docker:17.09.0-ce
    privileged: true
    when:
      branch: [develop]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - ./docker-deploy-latest.sh egar-public-ui
  deploy_docker_version_image:
    image: docker:17.09.0-ce
    privileged: true
    when:
      branch: [master]
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - ./docker-deploy-version.sh egar-public-ui
