FROM quay.io/ukhomeofficedigital/nodejs-base:v6.11.1

RUN rpm --rebuilddb
RUN yum -y install epel-release
RUN yum -y install redis

RUN mkdir -p /app
WORKDIR /app

COPY . /app

EXPOSE 8080
EXPOSE 9229
EXPOSE 9090
EXPOSE 9091

RUN chmod 755 start-debug.sh
ENTRYPOINT ["/app/start-debug.sh"]
